### PR TITLE
1.7 work,

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by StevenRS11** [comment]
Hey, just noticed this. Is this just update work, or are there functional changes in here as well?

**Comment by clienthax** [comment]
Just update work atm, the whole schematic thing out of my knowledge but it runs and the items etc are registered.

**Comment by StevenRS11** [comment]
Great. So, is the schematic stuff not working? Once I get back in town Ill merge this into my local branch and see whats going on either way.

**Comment by clienthax** [comment]
Well it uses blockids which are gone now

**Comment by StevenRS11** [comment]
Ok. Ill look into that- I imagine there is a simple way to get the vanilla block from an old block ID without to much of an issue. After that, I will probably need to revise the .schematic format.

**Comment by clienthax** [comment]
Any luck ?

**Comment by kayila** [comment]
Any chance this is going to be merged in soon? I'd love to see an official release with the 1.7 code Is the project still maintained?

**Comment by clienthax** [comment]
@kayila my code is nowhere near complete enough to work properly :P

**Pull request closed without merging**
