### PR TITLE
Commands are guaranteed to be ICommand, not CommandBase.

### PR DESCRIPTION
**Pull request by CannibalVox**
Currently some ChickenBones mods add commands that are based on ICommand but not CommandBase.  This causes a crash when a DimDoors command is compared to those commands.  The correct assumption is that all commands are ICommand, not CommandBase.

### CODE REVIEW

**Comment by SenseiKiwi** [comment]
That's odd. Why are we even performing that comparison in the first place? Steven must have included it for a reason. For the time being, I've asked him to merge the PR ASAP.

**Comment by CannibalVox** [comment]
I'm not sure it's DD that's performing the comparison but obviously performing it is a valid thing to do.

**Comment by SenseiKiwi** [comment]
Another user told me about what was going on and I realized why the comparisons are being performed. The comparisons are done by the help command to sort commands alphabetically for displaying. If you think about it, though, then that also means that support for that comparison must exist in CommandBase itself. Perhaps Steven added the comparison because at some point when our commands implemented ICommand and not CommandBase? I'm not sure. But the point is that the function is unnecessary - CommandBase already handles that for us. We can just remove it from our code.

**Comment by SenseiKiwi** [comment]
Fixed it in a separate commit along with some other stuff. No need for this PR anymore.

**Comment by CannibalVox** [comment]
Sounds rad- thanks a lot!

**Pull request closed without merging**
